export const FETCH_COMP_DETAIL_REQUEST = "FETCH_COMP_DETAIL_REQUEST";
export const FETCH_COMP_DETAIL_SUCCESS = "FETCH_COMP_DETAIL_SUCCESS";
export const FETCH_COMP_DETAIL_FAILURE = "FETCH_COMP_DETAIL_FAILURE";

export const FETCH_CURRENT_STOCK_DATA = "FETCH_CURRENT_STOCK_DATA";
export const FETCH_GRAPH_DATA = "FETCH_GRAPH_DATA";
