export const FETCH_COMP_DETAIL_REQUEST = "FETCH_COMP_DETAIL_REQUEST";
export const FETCH_COMP_DETAIL_SUCCESS = "FETCH_COMP_DETAIL_SUCCESS";
export const FETCH_COMP_DETAIL_FAILURE = "FETCH_COMP_DETAIL_FAILURE";

export const FETCH_QUOTE_REQUEST = "FETCH_QUOTE_REQUEST";
export const FETCH_QUOTE_SUCCESS = "FETCH_QUOTE_SUCCESS";
export const FETCH_QUOTE_FAILURE = "FETCH_QUOTE_FAILURE";

export const FETCH_PEERS_REQUEST = "FETCH_PEERS_REQUEST";
export const FETCH_PEERS_SUCCESS = "FETCH_PEERS_SUCCESS";
export const FETCH_PEERS_FAILURE = "FETCH_PEERS_FAILURE";

export const FETCH_GRAPH_DATA = "FETCH_GRAPH_DATA";
